#  File: /backend/app/config/skills_config.py
#  ✅ Central list of technical skills for NLP extraction
SKILL_KEYWORDS = [
    "Python", "Java", "JavaScript", "TypeScript", "C++", "C#", "Go", "Rust", "Ruby", "Kotlin",
    "HTML", "CSS", "SQL", "NoSQL", "PostgreSQL", "MongoDB", "MySQL", "Redis", 
    "AWS", "Azure", "GCP", "Docker", "Kubernetes", "Terraform", "CI/CD", 
    "React", "Next.js", "Vue", "Angular", "Node.js", "Express", "Flask", "Django", "Spring Boot",
    "REST", "GraphQL", "gRPC", "FastAPI",
    "Kafka", "RabbitMQ", "Celery",
    "Pandas", "NumPy", "TensorFlow", "PyTorch", "Scikit-learn",
    "Linux", "Shell", "Git", "Jira",
    "Agile", "Scrum", "DevOps", "SRE", "Security", "Monitoring", "Testing",
    "AI/ML", "AI", "Artificial Intelligence", "Machine Learning", "NLP", "LLM",
    "Data Science",
    "Selenium", "Automation Framework", 
    ".Net", "COM", "MFC",
]
# ✅ Centralized list of soft skills for NLP extraction: curtesy of Resume_Matcher:
SECTION_KEYWORDS = [    
    "Contact Information",
    "Personal Information",
    "Resume Summary",
    "Objective",
    "Executive Summary",
    "Professional Summary",
    "Career Objective",
    "Profile",
    "Professional Profile",
    "Work Experience",
    "Professional Experience",
    "Project Experience",
    "Volunteer Experience",
    "Military Experience",
    "Teaching Experience",
    "Clinical Experience",
    "Legal Experience",
    "Remote Work Experience",
    "Internships",
    "Fellowships",
    "Research Experience",
    "Fieldwork",
    "Practicums",
    "Consulting Experience",
    "Entrepreneurial Experience",
    "Leadership Roles",
    "Volunteer Leadership",
    "Board Memberships",
    "Advisory Roles",
    "Education",
    "Academic Background",
    "Qualifications",
    "Relevant Coursework",
    "Theses and Dissertations",
    "Continuing Education",
    "Skills",
    "Technical Skills",
    "Soft Skills",
    "Leadership Skills",
    "Language Skills",
    "Computer Skills",
    "Key Skills",
    "Core Competencies",
    "Technical Proficiencies",
    "Specializations",
    "Certifications",
    "Licenses",
    "Security Clearances",
    "Bar Admissions",
    "Medical Licensure",
    "Teaching Certifications",
    "Training",
    "Workshops",
    "Seminars Attended",
    "Professional Development Courses",
    "Awards and Honors",
    "Publications",
    "Patents",
    "Presentations",
    "Grants",
    "Scholarships",
    "Speaking Engagements",
    "Media Appearances",
    "Editorial Experience",
    "Achievements or Accomplishments",
    "Memberships and Associations",
    "Professional Affiliations",
    "Languages",
    "Interests and Hobbies",
    "Extracurricular Activities",
    "Community Involvement",
    "Artistic Portfolio",
    "Copyrights",
    "Trademarks",
    "Testimonials",
    "References",
    "Summary",
    "Education",
    "Experience",
    "Skills",
    "Projects",
    "Certifications",
    "Licenses",
    "Awards",
    "Patents",
    "Achievements",
    "Volunteer Work",
    "Volunteer Activities",
    "Extracurricular Activities",
    "Volunteer experience",
    "Honors",
    "Publications",
    "References",
    "Technical Skills",
    "Computer Skills",
    "Programming Languages",
    "Software Skills",
    "Soft Skills",
    "Language Skills",
    "Professional Skills",
    "Transferable Skills",
    "Work Experience",
    "Professional Experience",
    "Employment History",
    "Internship Experience",
    "Volunteer Experience",
    "Leadership Experience"
]

# ✅ Centralized list of soft skills for NLP extraction
# ✅ Centralized config for skill frequency logic to be used in /rountes/job.py:
MIN_SKILL_FREQUENCY = 2     # minmum number of frequency to count for emphasized skills
MAX_EMPHASIZED_SKILLS = 5   # maximum number of record to be stored as emphasized skills