# ✅ File: backend/app/services/resume_formatter.py
# Description: Formats resume text into a Word document with specific styles and sections.
# This module is used to generate a formatted resume in .docx format.
#

from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from io import BytesIO
from datetime import datetime
import os


def generate_formatted_resume_docx(resume_text: str, is_user_approved: bool) -> BytesIO:
    doc = Document()
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Segoe UI'
    font.size = Pt(12)

    lines = resume_text.strip().split('\n')
    output = BytesIO()

    # Get the directory of the current .py file
    current_dir = os.path.dirname(os.path.abspath(__file__))
    image_dir = os.path.join(current_dir, "resource")

    # Create a relative path to the image file
    image_path = os.path.join(image_dir, "horizontal_line.png")

    def add_line_break(doc_obj):
        doc_obj.add_paragraph(" ")

    def add_line(doc_obj):
        # Add an image line between sections
        doc.add_picture(image_path, width=None, height=None)  


    # Start formatting
    for i, line in enumerate(lines):
        line = line.strip()
        line = line.lstrip("-").strip()  # Remove the '-' and any extra whitespace
        
        if not line:
            continue

        # Assume first line is name
        if i == 0:
            p = doc.add_paragraph()
            run = p.add_run(line.upper())
            run.bold = True
            run.font.size = Pt(13.5)
            p.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
            continue

        # Assume second line is contact info
        if i == 1:            
            p = doc.add_paragraph()
            run = p.add_run(line)
            run.font.size = Pt(12)
            p.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
            #add_line(doc)
            continue

        # Section header detection
        if line.isupper() and len(line.split()) < 5:
            add_line(doc)
            p = doc.add_paragraph()
            run = p.add_run(line.upper())
            run.bold = True
            run.font.size = Pt(12)
            continue

        # Job or company formatting
        if "|" in line:
            parts = line.split("|")
            if len(parts) == 2:
                p = doc.add_paragraph()
                run = p.add_run(parts[0].strip())
                run.bold = True
                run.font.size = Pt(12)
                run = p.add_run(f" | {parts[1].strip()}")
                run.font.size = Pt(12)
                continue

        # Regular bullet or paragraph
        p = doc.add_paragraph(f"{line}", style='List Bullet')

    # Watermark/footnote
    if not is_user_approved:
        section = doc.sections[0]
        footer = section.footer
        p = footer.paragraphs[0]
        run = p.add_run("Generated by FindMyDreamJobs.com – Not yet user approved.")
        run.font.size = Pt(8)

    doc.save(output)
    output.seek(0)
    return output


# Return reference so user can integrate it easily.
resume_formatter_reference = generate_formatted_resume_docx
