"""Changed id in saved_jobs from uuid to integer

Revision ID: 00d565e9ca74
Revises: cb15ee3d45cb
Create Date: 2025-06-06 18:11:46.876853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d565e9ca74'
down_revision: Union[str, None] = 'cb15ee3d45cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Drop primary key constraint first
    op.drop_constraint('saved_jobs_pkey', 'saved_jobs', type_='primary')

    # Drop the old 'id' column (UUID)
    op.drop_column('saved_jobs', 'id')

    # Add new 'id' column as INTEGER PRIMARY KEY AUTOINCREMENT
    op.add_column('saved_jobs', sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False))

    # Recreate primary key constraint
    op.create_primary_key('saved_jobs_pkey', 'saved_jobs', ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved_jobs', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
