"""Fix foreign key relationships in JobMatch

Revision ID: 114950491783
Revises: 5bc34efa15b2
Create Date: 2025-03-25 14:14:44.737530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '114950491783'
down_revision: Union[str, None] = '5bc34efa15b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_matches', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_matches', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_matches', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_matches', 'match_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
    op.drop_index('ix_job_matches_user_id', table_name='job_matches')
    op.create_foreign_key(None, 'job_matches', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key(None, 'job_matches', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'job_matches', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_matches', type_='foreignkey')
    op.drop_constraint(None, 'job_matches', type_='foreignkey')
    op.drop_constraint(None, 'job_matches', type_='foreignkey')
    op.create_index('ix_job_matches_user_id', 'job_matches', ['user_id'], unique=False)
    op.alter_column('job_matches', 'match_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_matches', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_matches', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_matches', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
