"""Add ats_score_initial and ats_score_final to job_matches

Revision ID: 221466b1f52b
Revises: 89461d4e0b78
Create Date: 2025-03-26 17:05:24.748757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '221466b1f52b'
down_revision: Union[str, None] = '89461d4e0b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)
    acolumns = [col["name"] for col in inspector.get_columns("applications")]
    if "updated_at" not in acolumns:
        op.add_column('applications', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('applications', 'applied_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('job_matches', sa.Column('ats_score_initial', sa.Float(), nullable=True))
    op.add_column('job_matches', sa.Column('ats_score_final', sa.Float(), nullable=True))
    op.alter_column('job_matches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('job_matches', 'ats_score_before')
    op.drop_column('job_matches', 'ats_score_after')
    bcolumns = [col["name"] for col in inspector.get_columns("jobs")]
    if "updated_at" not in bcolumns:
        op.add_column('jobs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    if "added_at" in bcolumns:
        op.drop_column('jobs', 'added_at')
    if "posted_at" in bcolumns:
        op.drop_column('jobs', 'posted_at')
    op.add_column('resumes', sa.Column('ats_score_initial', sa.Float(), nullable=True))
    op.add_column('resumes', sa.Column('ats_score_final', sa.Float(), nullable=True))
    rcolumns = [col["name"] for col in inspector.get_columns("resumes")]
    if "updated_at" not in rcolumns:
        op.add_column('resumes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('resumes', 'parsed_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('resumes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('resumes', 'ats_score_before')
    op.drop_column('resumes', 'ats_score_after')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('resumes', sa.Column('ats_score_after', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('ats_score_before', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('resumes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('resumes', 'parsed_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('resumes', 'updated_at')
    op.drop_column('resumes', 'ats_score_final')
    op.drop_column('resumes', 'ats_score_initial')
    op.add_column('jobs', sa.Column('posted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'updated_at')
    op.add_column('job_matches', sa.Column('ats_score_after', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('job_matches', sa.Column('ats_score_before', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('job_matches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('job_matches', 'ats_score_final')
    op.drop_column('job_matches', 'ats_score_initial')
    op.alter_column('applications', 'applied_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('applications', 'updated_at')
    # ### end Alembic commands ###
