"""Refined application table: replaced created_at with applied_date, retained updated_at

Revision ID: 2de5de124d66
Revises: e564b68c37e1
Create Date: 2025-03-26 14:21:59.958329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de5de124d66'
down_revision: Union[str, None] = 'e564b68c37e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
