"""add applicants_count to jobs

Revision ID: 3ec549187c87
Revises: ba2dc12b9577
Create Date: 2025-12-20 16:18:31.406878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec549187c87'
down_revision: Union[str, None] = 'ba2dc12b9577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('applicants_count', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'applicants_count')
    # ### end Alembic commands ###
