"""Update saved_jobs table

Revision ID: 4991e9fa549e
Revises: d7b2a9e5b92d
Create Date: 2025-06-04 16:18:22.813475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4991e9fa549e'
down_revision: Union[str, None] = 'd7b2a9e5b92d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('saved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='saved_jobs_job_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='saved_jobs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='saved_jobs_pkey')
    )
    # ### end Alembic commands ###
