"""Update match_sore_initial, match_score_final

Revision ID: 53d57ddced25
Revises: 173593af22b5
Create Date: 2025-03-26 17:45:17.283115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '53d57ddced25'
down_revision: Union[str, None] = '173593af22b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)
   
    # ### commands auto generated by Alembic - please adjust! ###
    columns = [col["name"] for col in inspector.get_columns("job_matches")]
    if "match_score_final" not in columns:
        op.add_column('job_matches', sa.Column('match_score_final', sa.Float(), nullable=False))
    if "match_score" in columns:
        op.drop_column('job_matches', 'match_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('job_matches', 'match_score_final')
    # ### end Alembic commands ###
