"""Add missing fields & relationships

Revision ID: 5bc34efa15b2
Revises: 8f18f030bc97
Create Date: 2025-03-25 13:43:45.879381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc34efa15b2'
down_revision: Union[str, None] = '8f18f030bc97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('extracted_skills', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('added_at', sa.DateTime(), nullable=True))
    op.alter_column('jobs', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'job_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'job_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('jobs', 'added_at')
    op.drop_column('jobs', 'extracted_skills')
    # ### end Alembic commands ###
