"""add_jdi_scan_window_and_custom_sources

Revision ID: 616310ff25ce
Revises: e18296c70f76
Create Date: 2026-02-03 17:44:02.186537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '616310ff25ce'
down_revision: Union[str, None] = 'e18296c70f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('jdi_scan_window_days', sa.Integer(), nullable=False, server_default='7'))
    op.add_column('user_profiles', sa.Column('jdi_custom_source_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'jdi_custom_source_patterns')
    op.drop_column('user_profiles', 'jdi_scan_window_days')
    # ### end Alembic commands ###
