"""Add wizard_progress to users

Revision ID: 671ee15e4a18
Revises: f51845fdc101
Create Date: 2025-04-10 12:53:25.192918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671ee15e4a18'
down_revision: Union[str, None] = 'f51845fdc101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wizard_progress', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wizard_progress')
    # ### end Alembic commands ###
