"""Fix saved_jobs table

Revision ID: 87563b932fa0
Revises: 4991e9fa549e
Create Date: 2025-06-04 19:44:51.473931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87563b932fa0'
down_revision: Union[str, None] = '4991e9fa549e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('search_id', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('employer_name', sa.String(), nullable=False),
    sa.Column('employer_logo', sa.String(), nullable=True),
    sa.Column('employer_website', sa.String(), nullable=True),
    sa.Column('job_location', sa.String(), nullable=True),
    sa.Column('job_is_remote', sa.Boolean(), nullable=True),
    sa.Column('job_employment_type', sa.String(), nullable=True),
    sa.Column('job_salary', sa.String(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('job_apply_link', sa.String(), nullable=False),
    sa.Column('job_posted_at', sa.DateTime(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'search_id', name='uq_user_search')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_jobs')
    # ### end Alembic commands ###
