"""Update applications table to restore updated_at field

Revision ID: 89461d4e0b78
Revises: 2de5de124d66
Create Date: 2025-03-26 14:28:33.685413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89461d4e0b78'
down_revision: Union[str, None] = '2de5de124d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('applications', 'applied_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('job_matches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('jobs', 'posted_at')
    op.drop_column('jobs', 'added_at')
    op.add_column('resumes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('resumes', 'parsed_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('resumes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('resumes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('resumes', 'parsed_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('resumes', 'updated_at')
    op.add_column('jobs', sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('posted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'created_at')
    op.alter_column('job_matches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('applications', 'applied_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('applications', 'updated_at')
    # ### end Alembic commands ###
