"""Add ATS score fields to resumes

Revision ID: 8f18f030bc97
Revises: f3e6921bb214
Create Date: 2025-03-25 12:53:47.136380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f18f030bc97'
down_revision: Union[str, None] = 'f3e6921bb214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('ats_score_before', sa.Float(), nullable=True))
    op.add_column('resumes', sa.Column('ats_score_after', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'ats_score_after')
    op.drop_column('resumes', 'ats_score_before')
    # ### end Alembic commands ###
