"""Change extracted_skills to ARRAY

Revision ID: 921275e54062
Revises: b64a9fea6cb3
Create Date: 2025-04-03 09:51:32.110007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '921275e54062'
down_revision: Union[str, None] = 'b64a9fea6cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'extracted_skills',
               existing_type=sa.TEXT(),
               type_=postgresql.ARRAY(sa.String()),
               postgresql_using="extracted_skills::text[]",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'extracted_skills',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
