"""Add optimization and ATS score columns

Revision ID: 971a393b2ec2
Revises: 2b73ea44361c
Create Date: 2025-03-22 12:56:13.763756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971a393b2ec2'
down_revision: Union[str, None] = '2b73ea44361c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('ats_score_before', sa.Integer(), nullable=True))
    op.add_column('job_matches', sa.Column('ats_score_after', sa.Integer(), nullable=True))
    op.alter_column('job_matches', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_matches', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_matches', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_matches', 'match_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_job_matches_user_id'), 'job_matches', ['user_id'], unique=False)
    op.drop_constraint('job_matches_job_id_fkey', 'job_matches', type_='foreignkey')
    op.drop_constraint('job_matches_resume_id_fkey', 'job_matches', type_='foreignkey')
    op.drop_constraint('job_matches_user_id_fkey', 'job_matches', type_='foreignkey')
    op.add_column('resumes', sa.Column('optimized_text', sa.Text(), nullable=True))
    op.add_column('resumes', sa.Column('is_ai_generated', sa.Boolean(), nullable=True))
    op.add_column('resumes', sa.Column('is_user_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'is_user_approved')
    op.drop_column('resumes', 'is_ai_generated')
    op.drop_column('resumes', 'optimized_text')
    op.create_foreign_key('job_matches_user_id_fkey', 'job_matches', 'users', ['user_id'], ['id'])
    op.create_foreign_key('job_matches_resume_id_fkey', 'job_matches', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key('job_matches_job_id_fkey', 'job_matches', 'jobs', ['job_id'], ['id'])
    op.drop_index(op.f('ix_job_matches_user_id'), table_name='job_matches')
    op.alter_column('job_matches', 'match_score',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('job_matches', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_matches', 'resume_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_matches', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('job_matches', 'ats_score_after')
    op.drop_column('job_matches', 'ats_score_before')
    # ### end Alembic commands ###
