"""Change extracted_skills to JSONB

Revision ID: a0148ad7c7ca
Revises: 921275e54062
Create Date: 2025-04-03 10:13:48.495122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy.dialects.postgresql as pg

# revision identifiers, used by Alembic.
revision: str = 'a0148ad7c7ca'
down_revision: Union[str, None] = '921275e54062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "extracted_skills")
    op.add_column("jobs", sa.Column("extracted_skills", pg.JSONB(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "extracted_skills")
    op.add_column("jobs", sa.Column("extracted_skills", sa.ARRAY(sa.String), nullable=True))

    # ### end Alembic commands ###
