"""Add user_id to jobs

Revision ID: b64a9fea6cb3
Revises: f17abfe9c725
Create Date: 2025-04-02 11:19:55.547526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64a9fea6cb3'
down_revision: Union[str, None] = 'f17abfe9c725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_matches', 'match_score_final',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('jobs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('job_link', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('required_experience', sa.String(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'])
    op.drop_column('jobs', 'job_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'required_experience')
    op.drop_column('jobs', 'job_link')
    op.drop_column('jobs', 'user_id')
    op.alter_column('job_matches', 'match_score_final',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
