"""Changed id in saved_jobs from uuid to integer

Revision ID: cb15ee3d45cb
Revises: d6851b9178fd
Create Date: 2025-06-06 16:38:35.567349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb15ee3d45cb'
down_revision: Union[str, None] = 'd6851b9178fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Drop primary key constraint temporarily
    op.drop_constraint('saved_jobs_pkey', 'saved_jobs', type_='primary')

    # Alter column type: UUID → INTEGER
    op.alter_column('saved_jobs', 'id',
        type_=sa.Integer(),
        existing_type=sa.dialects.postgresql.UUID(),
        autoincrement=True
    )

    # Re-add primary key constraint
    op.create_primary_key('saved_jobs_pkey', 'saved_jobs', ['id'])



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
