"""Fix user_id type in saved_jobs

Revision ID: d6851b9178fd
Revises: 87563b932fa0
Create Date: 2025-06-05 17:34:57.261602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6851b9178fd'
down_revision: Union[str, None] = '87563b932fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE saved_jobs ALTER COLUMN user_id TYPE INTEGER USING user_id::integer')

    op.create_foreign_key(None, 'saved_jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_jobs', type_='foreignkey')
    op.alter_column('saved_jobs', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
