"""Update saved_jobs table

Revision ID: d7b2a9e5b92d
Revises: 836224369440
Create Date: 2025-06-03 13:49:00.396069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7b2a9e5b92d'
down_revision: Union[str, None] = '836224369440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_jobs', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column('saved_jobs', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('saved_jobs', sa.Column('job_location', sa.String(), nullable=True))
    op.add_column('saved_jobs', sa.Column('job_id', sa.Integer(), nullable=True))
    op.add_column('saved_jobs', sa.Column('saved_at', sa.DateTime(), nullable=False))
    op.alter_column('saved_jobs', 'job_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_saved_jobs_id', table_name='saved_jobs')
    op.create_foreign_key(None, 'saved_jobs', 'jobs', ['job_id'], ['id'])
    op.drop_column('saved_jobs', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_jobs', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'saved_jobs', type_='foreignkey')
    op.create_index('ix_saved_jobs_id', 'saved_jobs', ['id'], unique=False)
    op.alter_column('saved_jobs', 'job_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('saved_jobs', 'saved_at')
    op.drop_column('saved_jobs', 'job_id')
    op.drop_column('saved_jobs', 'job_location')
    op.drop_column('saved_jobs', 'company_name')
    op.drop_column('saved_jobs', 'job_title')
    # ### end Alembic commands ###
