"""add JDI tables: user_profiles, user_integrations, jdi_candidates

Revision ID: e18296c70f76
Revises: 3ec549187c87
Create Date: 2026-02-01 16:12:57.776129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e18296c70f76'
down_revision: Union[str, None] = '3ec549187c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_integrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_integration_provider')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jdi_min_score', sa.Integer(), nullable=False),
    sa.Column('jdi_sources_enabled', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jdi_base_resume_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jdi_resume_select_mode', sa.String(length=20), nullable=False),
    sa.Column('jdi_resume_keyword_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('jdi_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_message_id', sa.String(), nullable=True),
    sa.Column('job_url_raw', sa.Text(), nullable=True),
    sa.Column('job_url_canonical', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('employment_type', sa.Text(), nullable=True),
    sa.Column('salary_text', sa.Text(), nullable=True),
    sa.Column('jd_text', sa.Text(), nullable=True),
    sa.Column('jd_hash', sa.String(length=64), nullable=True),
    sa.Column('jd_extraction_confidence', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('match_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_resume_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['selected_resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_url_canonical', name='uq_jdi_user_job_url')
    )
    op.create_index('ix_jdi_user_seen', 'jdi_candidates', ['user_id', 'seen_at'], unique=False)
    op.create_index('ix_jdi_user_status_score', 'jdi_candidates', ['user_id', 'status', 'match_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jdi_user_status_score', table_name='jdi_candidates')
    op.drop_index('ix_jdi_user_seen', table_name='jdi_candidates')
    op.drop_table('jdi_candidates')
    op.drop_table('user_profiles')
    op.drop_table('user_integrations')
    # ### end Alembic commands ###
