"""Mkae match_score_final nullable

Revision ID: f17abfe9c725
Revises: 3c5b4ccb5967
Create Date: 2025-03-26 19:10:41.960200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17abfe9c725'
down_revision: Union[str, None] = '3c5b4ccb5967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('match_score_final', sa.Float(), nullable=True))
    op.drop_column('job_matches', 'match_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('job_matches', 'match_score_final')
    # ### end Alembic commands ###
