"""Add unique constraint on job_matches

Revision ID: f51845fdc101
Revises: 6a0194666473
Create Date: 2025-04-10 10:59:09.056499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51845fdc101'
down_revision: Union[str, None] = '6a0194666473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_job_resume_combination', 'job_matches', ['job_id', 'resume_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_job_resume_combination', 'job_matches', type_='unique')
    # ### end Alembic commands ###
