"""Updated database schema and match relationship

Revision ID: fbed949a6830
Revises: 114950491783
Create Date: 2025-03-25 15:39:13.516480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbed949a6830'
down_revision: Union[str, None] = '114950491783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('matched_skills', sa.Text(), nullable=True))
    op.add_column('job_matches', sa.Column('missing_skills', sa.Text(), nullable=True))
    op.add_column('job_matches', sa.Column('calculated_at', sa.DateTime(), nullable=True))
    op.alter_column('job_matches', 'ats_score_before',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('job_matches', 'ats_score_after',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('jobs', sa.Column('posted_at', sa.DateTime(), nullable=True))
    op.drop_column('jobs', 'posted_date')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               postgresql_using="created_at::timestamp without time zone",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('users', 'updated_at')
    op.add_column('jobs', sa.Column('posted_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'posted_at')
    op.alter_column('job_matches', 'ats_score_after',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('job_matches', 'ats_score_before',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('job_matches', 'calculated_at')
    op.drop_column('job_matches', 'missing_skills')
    op.drop_column('job_matches', 'matched_skills')
    # ### end Alembic commands ###
