# ✅ File: backend/app/routes/download.py
# Description: Exports optimized resume in Word (.docx) format with formatting & watermark
# Wwatermark will be removed if the resume is approved by the user.

from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from app.database.connection import get_db
from app.models.resume import Resume
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from io import BytesIO
from datetime import datetime

router = APIRouter()

@router.get("/download-optimized-resume/{resume_id}", tags=["Resume"])
def download_optimized_resume(resume_id: int, db: Session = Depends(get_db)):
    resume = db.query(Resume).filter(Resume.id == resume_id).first()
    if not resume:
        raise HTTPException(status_code=404, detail="Resume not found.")
    if not resume.optimized_text:
        raise HTTPException(status_code=400, detail="Resume not yet optimized.")

    doc = Document()
    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(11)

    # Format optimized resume text
    lines = resume.optimized_text.strip().split('\n')
    for line in lines:
        line = line.strip()
        if line.startswith("**") and line.endswith("**"):
            p = doc.add_paragraph()
            run = p.add_run(line.replace("**", ""))
            run.bold = True
            run.font.size = Pt(14)
        elif line.startswith("- "):
            doc.add_paragraph(line[2:], style='List Bullet')
        else:
            doc.add_paragraph(line)

    # Add watermark in footer if not approved
    if not resume.is_user_approved:
        section = doc.sections[0]
        footer = section.footer
        footer_paragraph = footer.paragraphs[0]
        footer_paragraph.text = "Generated by findmydreamjobs.com — Not Yet Approved"
        footer_paragraph.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
        footer_paragraph.runs[0].italic = True
        footer_paragraph.runs[0].font.size = Pt(8)

    output = BytesIO()
    doc.save(output)
    output.seek(0)

    filename = f"Resume_{resume_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    return StreamingResponse(
        output,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
